/** Generated by scripts/build-config.mjs — do not edit by hand on Netlify. */
export const runtimeConfig = {
  supabaseUrl: "https://xdgprhpikimmoramxrbs.supabase.co",
  supabaseAnonKey: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhkZ3ByaHBpa2ltbW9yYW14cmJzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODM0NTk3OTgsImV4cCI6MjA5OTAzNTc5OH0.DgQIFKB5ncHPpDs2PEkULPtDcBU3sevCx_xWp8eFhds",
};
