-- Privacy-conscious product analytics for the HomePassportAI admin dashboard.
-- Events contain no free-form properties or user-provided content. They begin
-- accumulating only after this migration and the matching application code
-- are deployed. Historical values are not backfilled.

create table if not exists public.analytics_events (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users (id) on delete set null,
  event_name text not null check (
    event_name in (
      'appliance_added',
      'room_scanned',
      'document_saved',
      'manual_lookup',
      'inventory_viewed',
      'reports_viewed'
    )
  ),
  country_code text check (country_code is null or country_code ~ '^[A-Z]{2}$'),
  device_type text not null default 'other' check (
    device_type in ('ios', 'android', 'other')
  ),
  created_at timestamptz not null default now()
);

create index if not exists analytics_events_created_at_idx
  on public.analytics_events (created_at desc);
create index if not exists analytics_events_event_name_idx
  on public.analytics_events (event_name);
create index if not exists analytics_events_country_code_idx
  on public.analytics_events (country_code)
  where country_code is not null;
create index if not exists analytics_events_device_type_idx
  on public.analytics_events (device_type);

alter table public.analytics_events enable row level security;

-- Deliberately no browser-facing policies. Events are inserted and selected only
-- by authenticated Netlify/local server functions using the service role. This
-- prevents clients from spoofing dimensions or reading aggregate source data.

create or replace function public.admin_dashboard_database_stats()
returns json
language sql
security definer
set search_path = public, storage
as $$
  select json_build_object(
    'appliances_added', (select count(*)::int from public.appliances),
    'homes_with_inventory', (
      select count(distinct user_id)::int from public.appliances
    ),
    'rooms_with_items', (
      select count(*)::int
      from (
        select distinct user_id, room
        from public.appliances
      ) rooms
    ),
    'distinct_rooms', (
      select count(*)::int
      from (
        select distinct user_id, room
        from public.appliances
      ) rooms
    ),
    'storage_bytes', (
      select coalesce(sum(
        case
          when metadata->>'size' ~ '^[0-9]+$' then (metadata->>'size')::bigint
          else 0
        end
      ), 0)::bigint
      from storage.objects
    )
  );
$$;

revoke all on function public.admin_dashboard_database_stats() from public;
revoke all on function public.admin_dashboard_database_stats() from anon;
revoke all on function public.admin_dashboard_database_stats() from authenticated;
grant execute on function public.admin_dashboard_database_stats() to service_role;

create or replace function public.admin_analytics_aggregates()
returns json
language sql
security definer
set search_path = public
as $$
  select json_build_object(
    'rooms_scanned', (
      select count(*)::int
      from public.analytics_events
      where event_name = 'room_scanned'
    ),
    'manual_lookups', (
      select count(*)::int
      from public.analytics_events
      where event_name = 'manual_lookup'
    ),
    'documents_saved', (
      select count(*)::int
      from public.analytics_events
      where event_name = 'document_saved'
    ),
    'total_events', (select count(*)::int from public.analytics_events),
    'events_since', (select min(created_at) from public.analytics_events),
    'by_country', coalesce((
      select json_agg(row_to_json(t) order by t.count desc, t.country_code)
      from (
        select country_code, count(*)::int as count
        from public.analytics_events
        where country_code is not null
        group by country_code
      ) t
    ), '[]'::json),
    'by_device', coalesce((
      select json_agg(row_to_json(t) order by t.count desc, t.device_type)
      from (
        select device_type, count(*)::int as count
        from public.analytics_events
        group by device_type
      ) t
    ), '[]'::json),
    'by_feature', coalesce((
      select json_agg(row_to_json(t) order by t.count desc, t.event_name)
      from (
        select event_name, count(*)::int as count
        from public.analytics_events
        group by event_name
      ) t
    ), '[]'::json)
  );
$$;

revoke all on function public.admin_analytics_aggregates() from public;
revoke all on function public.admin_analytics_aggregates() from anon;
revoke all on function public.admin_analytics_aggregates() from authenticated;
grant execute on function public.admin_analytics_aggregates() to service_role;

-- Keep the older inventory helper for backward compatibility with earlier admin code.
create or replace function public.admin_inventory_stats()
returns json
language sql
security definer
set search_path = public
as $$
  select json_build_object(
    'total_items', (select count(*)::int from public.appliances),
    'users_with_inventory', (select count(distinct user_id)::int from public.appliances)
  );
$$;

revoke all on function public.admin_inventory_stats() from public;
revoke all on function public.admin_inventory_stats() from anon;
revoke all on function public.admin_inventory_stats() from authenticated;
grant execute on function public.admin_inventory_stats() to service_role;
